### ISSUE TITLE
Python 3.11.7 への対応

### ISSUE THREAD

**Issue by ryo-ma** [c-3lab/ckanext-feedback#103]
CKAN2.10ではPython 3.9がうまく動くと書かれているが3.11.7でも動作対応を行う
https://github.com/ckan/ckan/wiki/CKAN-2.10-(aka-master-@1-Dec-2022)-install-on-Ubuntu-22.04

**Comment by To-Ki-O** [comment]
`ckan-docker/ckan/Dockerfile.dev` に `FROM ckan/ckan-dev:2.10.3`と記載があるため、
`ckan/ckan-dev:2.10.3`のイメージ内のPython Versionを変更する必要があると考えられる。

`ckan/ckan-dev:2.10.4` のイメージは以下のリポジトリの`Dockerfile`から生成されている。
[ckan-docker-base](https://github.com/ckan/ckan-docker-base)

そのため、上記リポジトリからPython3.11.7を使っているイメージをローカルに作成し、それを使ってCKANを構築することで、
Python3.11.7がインストールされたCKANが構築できると考えられる。
 
流れとしては以下のように考えている。
※ CKANでは`ckan/ckan-dev`イメージを参照しており、`ckan/ckan-dev`イメージでは`ckan/ckan-base`を参照している。
1. `ckan-docker-base/ckan-2.10/base`にて`make build`を行い、Python3.11.7を使うイメージを作成
2. `ckan-docker-base/ckan-2.10/dev`にて1番のイメージを用いて、`make build`を行う
3. 2番のイメージを用いて、CKANの構築を行う

**Comment by To-Ki-O** [comment]
`ckan-docker-base/ckan-2.10/base`において、`alpine:3.10`が利用されている。

`alpine:3.17`にはPython3.10系が紐づいており、Pytnon3.11.7をインストールするのは、難しいかと思われる。
そのため、Python3.11.7に紐づいている`alpine:3.19`を利用して`Dockerfile`を構築する
[Python3.11.7が紐づいたalpine:3.19のDockerHub](https://hub.docker.com/layers/library/python/3.11.7-alpine/images/sha256-6aa46819a8ff43850e52f5ac59545b50c6d37ebd3430080421582af362afec97?context=explore)

`alpine:3.19`では、`pip`が利用できなくなり、`pipx`を代わりに用いるようになったため、
`Dockerfile`を見直しながら、再度作成していく必要があると考えられる。

**Comment by To-Ki-O** [comment]
`alpine:3.19`では`pip`が利用できず、`pipx`を利用する必要がある。
しかし、`pipx`ではCKANのインストールがうまくいかない。

そのため、`alpine:3.18`を採用した。
`alpine:3.18`ではPython3.11.7は指定できず、Python3.11.8であれば指定可能であった。

そのため、手元でも動作確認は、Python3.11.8で行う形としたい。

**Comment by To-Ki-O** [comment]
また、本Issueを`ckanext-feedback`に反映させる場合、CKAN準拠のOSSから遠ざかる懸念がある。
そのため、構築手順をWikiに記載し、動作確認はそれぞれの手元で行うこととし、
本体への反映はしないものとする。

**Comment by To-Ki-O** [comment]
動作上、特に問題はありませんでした。

**Comment by To-Ki-O** [comment]
#145 がクローズした際にクローズする
