### ISSUE TITLE
★0のコメントもRaiting集計対象に含まれている。

### ISSUE THREAD

**Issue by KeiIshidaAbel** [c-3lab/ckanext-feedback#154]
## 再現手順

1. あるデータセットに、Rating3のコメントを追加し、承認する
    - この状態で、そのデータセットを表示すると、★3.0 と表示される。
2. 前項と同じデータセットに、Rating無しのRequestコメントを追加する。
    - この状態で、そのデータセットを表示すると、★3.0 と表示される。
3. 前項で追加したコメントを承認する。
    - この状態で、そのデータセットを表示すると、★1.5 と表示される。
    - Rating無しのRequestコメントも含めたコメント数でRatingを集計しているように見える

**Comment by KeiIshidaAbel** [comment]
- rating の平均値を求めている以下のメソッドが原因の可能性がある
  - ckanext/feedback/services/management/comments.py の  refresh_resources_comments
  - ckanext/feedback/services/resource/summary.py の refresh_resource_summary

**Comment by To-Ki-O** [comment]
こちら対応いたします。
