### ISSUE TITLE
テーブル作成、更新方法の変更

### ISSUE THREAD

**Issue by YukiNakamuraAbel** [c-3lab/ckanext-feedback#181]
現状はfeedback initによるテーブル再作成となっているが、CKANのベストプラクティスに則りmigrationによる作成、更新に変更する。
・参考URL
https://docs.ckan.org/en/latest/extensions/best-practices.html

**Comment by keita-yasuda** [comment]
対応後にQuick Startの手順も要修正。
https://github.com/c-3lab/ckanext-feedback/pull/183#discussion_r1625884387

**Comment by keita-yasuda** [comment]
使用するコマンドは`ckan db`系に統一する方針。
https://github.com/c-3lab/ckanext-feedback/pull/183#discussion_r1625868553
