### ISSUE TITLE
利活用方法 詳細画面のURL 遷移エラー

### ISSUE THREAD

**Issue by To-Ki-O** [c-3lab/ckanext-feedback#184]
利活用方法 詳細画面 URLにURL形式(`https://XXXX`)以外の文字列を登録している状態で発生する。
登録されている文字列のリンクをクリックするとエラー画面が表示される。

**Comment by To-Ki-O** [comment]
こちら対応いたします。

**Comment by ryo-ma** [comment]
ここはそもそもURLの入力を想定なのでURLのバリデーションを入力時に行いましょう。

**Comment by To-Ki-O** [comment]
備忘　→　URL入力欄に薄くExample(https://example.comのようなもの)を表示する
