### ISSUE TITLE
データセット名を変更した場合も変更前の名前が表示される

### ISSUE THREAD

**Issue by Sheile** [c-3lab/ckanext-feedback#60]
データセット名を「dataset1」で作成した後、Manageボタンから「Changed」に変更した場合、以下のようになる。

```
ckan=# select * from package;
-[ RECORD 1 ]-----+-------------------------------------
id                | 0ed05aa4-9ad9-408d-bd22-8170b7b517d7
name              | dataset1
title             | Changed
～以下略～
```

CKANの画面上では「Changed」として表示されるが、拡張機能では`package.title`ではなく`package.name`を使っているため、変更前の「dataset1」が表示されてしまう。
整合性が無くてわかりづらいが、CKANとしては以下のように扱っているように見える。

- Package(Dataset)
  - id: 使用しない
  - name: URLに使用する一意なキー
  - title: 画面表示に使う名称
- Resource
  - id: URLに使用する一意なキー
  - name: 画面表示に使う名称

![image](https://user-images.githubusercontent.com/191358/229090477-33f9255f-f355-4a41-9fd7-e8b94ca86fa5.png)

![image](https://user-images.githubusercontent.com/191358/229090878-0323d3c4-a579-4af8-9ba3-4771bca778b2.png)

**Comment by YukiNakamuraAbel** [comment]
以下PRで対応済み
- コメント管理画面
https://github.com/c-3lab/ckanext-feedback/pull/157
- 利活用一覧画面
https://github.com/c-3lab/ckanext-feedback/pull/56
