### ISSUE TITLE
利活用方法へのコメントに対する返信

### ISSUE THREAD

**Issue by urabe0225** [c-3lab/ckanext-feedback#80]
データセットに対するコメントには「reply」ボタンが表示されるのに対し、利活用方法に対して入力されたコメントには「reply」ボタンが表示されない

**Comment by To-Ki-O** [comment]
利活用方法に対するコメントについて

利活用方法登録者になりすました第３者が悪意を持って返信したコメントを管理者が判断できないため、
利活用方法に対して入力されたコメントへのReplyは実装していません。

そのため、正常な動作になります。
