### ISSUE TITLE
改行が含まれているコメントに対して返信をすることができない

### ISSUE THREAD

**Issue by To-Ki-O** [c-3lab/ckanext-feedback#87]
# 改行が含まれているコメントに対して返信をすることができない

## 確認している動作

* 改行が含まれたコメントに返信を送信しようとするとエラー(400)が返される
    * 返信コメント内に改行が含まれている場合も同様

## 原因

* `resource_id`と`content`が空欄の際にエラー(400)が返されるようになっている
    * そのため、改行が原因で空欄扱いになっている可能性がある

* 詳細は調査中

**Comment by To-Ki-O** [comment]
## 2023/11/30 追記

* 改行がある場合に`resource_comment_id`が返却されていないことを確認

**Comment by ryo-ma** [comment]
原因はわかりました。タグ内のJS上にテンプレート上で埋め込んだ改行が評価されてしまっているため syntax error になっているんです。

<img width="1320" alt="スクリーンショット 2023-11-30 17 18 57" src="https://github.com/c-3lab/ckanext-feedback/assets/6661165/0d029461-d3f2-48e2-8ad5-87cfc5ac8559">

**Comment by To-Ki-O** [comment]
ありがとうございます。

現在、`ckanext/feedback/assets/js/comment.js`の`checkRatingAndCommentExists()`内で
改行を空白行と置換する処理を記述したところ、正常に動作することを確認しました。

こちらの対応でプルリクエストを一度あげようかと考えているのですが、良いでしょうか？

**Comment by ryo-ma** [comment]
というかこの実装は危険ですね。JSが評価可能の場所なのでクロスサイトスクリプティングを行える可能性もあります。
それを踏まえた修正が必要です。

**Comment by ryo-ma** [comment]
@To-Ki-O 可能であれば早急に対応したいです。そもそもここのJSに受け渡す流れになっている実装から見直すべきです。

**Comment by To-Ki-O** [comment]
承知しました。
